### ISSUE TITLE
hypexport returns global info only

### ISSUE THREAD

**Issue by hwiorn** [karlicoss/hypexport#7]
I simply tested it like this.
```sh
python3 -m hypexport.export --username "SOME_ID" --token "SOME_TOKEN" > hypothesis.json
```

```
{
  "annotations": [],
  "profile": {
    "authority": "hypothes.is",
    "features": {
      "client_display_names": false,
      "embed_cachebuster": false,
      "notebook_launch": true
    },
    "groups": [
      {
        "id": "__world__",
        "name": "Public",
        "public": true
      },
      {
        "id": "OMITTED",
        "name": "Audio signal analysis",
        "public": false,
        "url": "https://hypothes.is/groups/OMITTED/audio-signal-analysis"
      },
      {
        "id": "OMITTED",
        "name": "Data science",
        "public": false,
        "url": "https://hypothes.is/groups/OMITTED/data-science"
      },
      {
        "id": "OMITTED",
        "name": "General",
        "public": false,
        "url": "https://hypothes.is/groups/OMITTED/general"
      }
    ],
    "preferences": {},
    "user_info": {
      "display_name": null
    },
    "userid": "acct:OMITTED@hypothes.is"
  }
}                         
```

This output differs from [annotation.json](https://raw.githubusercontent.com/taniki/netrights-dashboard-mockup/master/_data/annotations.json) of [HPI demo.](https://github.com/karlicoss/HPI/blob/master/demo.py)

I saw [your comment](https://github.com/karlicoss/HPI/issues/110#issuecomment-731977892).
Is the hypothesis annotation structure changed?
Or do I have to change some settings in hypothesis?

**Comment by hwiorn** [comment]
I got it.
The username does not mean **login(account) ID**.
The hypexport uses the username as a search filter.
https://github.com/karlicoss/hypexport/blob/c92c6ee997291ba33cd03df56a94c0363a3aa5b3/src/hypexport/export.py#L14

So It need to be `acct:OMITTED@hypothes.is` or `OMITTED@hypothes.is` not "SOME_ID".

**Comment by karlicoss** [comment]
Hi! Glad you've figured this out, but not sure I understand -- what did you pass to `--username` instead of the username? 

In my hypexport job, I'm just passing `--username karlicoss` and it seems to work, no need for `karlicoss@hypothes.is`

**Comment by hwiorn** [comment]
@karlicoss I used my email account. `Hypothes.is` accepts both email account and username. So I thought `--username` and `--token` are authentication options. `Hypothes.is` handles a `username` as `username@hypothes.is` in their API. So it also works without `@hypothes.is`.
